#Configuracion
#Sat Jun 06 23:09:18 MST 2026
amenity.folder=C\:\\Users\\any_u\\OneDrive\\Documentos\\proyecto-final\\src\\assets\\img\\serv
main.window.height=868
main.window.width=1616
main.window.x=-8
main.window.y=-8
registration.window.height=736
registration.window.width=1376
registration.window.x=-8
registration.window.y=-8
room.image.folder=C\:\\Users\\any_u\\OneDrive\\Documentos\\Eclipse Java\\proyecto-final\\src\\assets\\img\\rooms
users.export.pdf=C\:\\Users\\any_u\\OneDrive\\Documentos
