#Configuracion
<<<<<<< HEAD
#Mon Jun 01 16:05:29 MST 2026
=======
#Mon Jun 01 15:53:51 MST 2026
>>>>>>> 3cc26ecfe5276e51100d44cb92cbe8a5d2f79f5c
amenity.folder=C\:\\Users\\any_u\\OneDrive\\Documentos\\proyecto-final\\src\\assets\\img\\serv
main.window.height=830
main.window.width=1550
main.window.x=-7
main.window.y=-7
registration.window.height=736
registration.window.width=1376
registration.window.x=-8
registration.window.y=-8
room.image.folder=C\:\\Users\\any_u\\OneDrive\\Documentos\\Eclipse Java\\proyecto-final\\src\\assets\\img\\icons
users.export.pdf=C\:\\Users\\any_u\\OneDrive\\Documentos
