#Configuracion
#Tue May 05 20:20:18 MST 2026
registration.window.height=736
registration.window.width=1376
registration.window.x=-8
registration.window.y=-8
users.export.pdf=C\:\\Users\\any_u\\Downloads
